version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  node: circleci/node@4.7.0

executors:
  default:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.version >>
        environment: &ruby_environment
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_APP_CONFIG: ./.bundle/
          BUNDLE_PATH: ./vendor/bundle/
          DB_HOST: localhost
          DB_USER: root
          RAILS_ENV: test
          ALLOW_NOPAM: true
          CONTINUOUS_INTEGRATION: true
          DISABLE_SIMPLECOV: true
          PAM_ENABLED: true
          PAM_DEFAULT_SERVICE: pam_test
          PAM_CONTROLLED_SERVICE: pam_test_controlled
      - image: cimg/postgres:12.7
        environment:
          POSTGRES_USER: root
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: circleci/redis:5-alpine

commands:
  install-system-dependencies:
    steps:
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libicu-dev libidn11-dev libprotobuf-dev protobuf-compiler

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - install-system-dependencies
      - ruby/install-deps
      - node/install-packages:
          cache-version: v1
          pkg-manager: yarn
      - run:
          name: Precompile assets
          command: ./bin/rails assets:precompile
      - persist_to_workspace:
          root: .
          paths:
            - ./mastodon/public/assets
            - ./mastodon/public/packs-test

  test:
    parameters:
      version:
        type: string
    executor:
      name: default
      version: << parameters.version >>
    parallelism: 4
    steps:
      - checkout
      - install-system-dependencies
      - run:
          name: Install FFMPEG
          command: sudo apt-get install -y ffmpeg
      - ruby/install-deps:
          key: gems-v1
      - attach_workspace:
          at: .
      - run:
          command: dockerize -wait tcp://localhost:5432 -wait tcp://localhost:6379 -timeout 1m
          name: Wait for PostgreSQL and Redis
      - ruby/rspec-test

  test-migrations:
    executor: default
    steps:
      - install-system-dependencies
      - run:
          name: Create database
          command: ./bin/rails db:create
      - run:
          name: Run migrations
          command: ./bin/rails db:migrate

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          name: test-ruby<< matrix.version >>
          matrix:
            parameters:
              version:
                - 2.6
                - 2.7
                - 3.0
          requires:
            - build
      - test-migrations
      - node/run:
          cache-version: v1
          name: test-webui
          pkg-manager: yarn
          requires:
            - build
          version: '14'
          yarn-run: test:jest
