language: node_js
node_js:
- stable
sudo: false
script:
- npm install
- npm test
branches:
  only:
  - "/^\\d+\\.\\d+/"
deploy:
  provider: npm
  email: manager@mathjax.org
  api_key:
    secure: TkVYMGGCRAbo1BqsL7xK+ZY2hBJHyJ1obGoSH/7LYEy+/IxrOSnU90YHtmOyTOExZgwE2HM4f5xetXWsT+kK8Z9Lg90553SRVujBaBk8Vz5c+tYX7h2ufg6wV3bYJjKyvEwARuqGa4uTy+KXM0spSDs7M/wx8sd2DphL7o4wELWrQHZey/K/WKR2MYt/C6rXsdMyBusPiS2wEwG6Ef5utZ9AyZUkphs1kuRdFCZenmjmNREeuKiid8gsx4I6kY/biqOUIr7yA/chIFpoUNaYvmsiTI35oUfL37KyuDqoB+cvDIhbkPAfflt+SlK7MvnMDFuQK2qwXvHAJZ5eurVZGymUN0SOtiGfXls+aeSsFoDM2Gjmghc1hkm4EKy6ZybCgII88GaMaDsnPK2NygY6SobUjSy4lrQWsOFuRjqz9w430/CwS8t0TaZX8nplo/ZNp5Yl18hW5qMLlyNse3q5DG5YytFMvyul6w23ksDnhpxHSkCYahuzL1hPwe30FzRjbaRIE3sDembCJ8X5XvSfSSNM0Gw2wuJ1UPmk/eivyIO/jfFYz6NsG5Q0iZCSNKIHQDe7fL4sgcmaaEf5p32ABmCVJGs45hrFEy7Mn2qwHaKanL/X8Q4F5laM6+fDv2eYLCqDq2mgbYftBqlOAldSFCjga47QaTGVuc80Dki6JXI=
  on:
    tags: true
